<?php
/**
 * Programa de Configuracao
 * -------------------------------------------------------------------------------------------
 * @author Guilherme Galvão
 * @version 1.0
 * @copyright 2023
 */

//-----------------------------------------------
// seta configuracoes (conexao)
//-----------------------------------------------
$config = array("host"     =>  "localhost"         ,
		 "user"     => "monteoli_server"    ,
		 "pass"     => "p@nd@320"           ,
		 "database" => "monteoli_monteoliva");

//-----------------------------------------------
// Configuracao das tabelas
//-----------------------------------------------
$TB_USUARIO = "tb_users";
$TB_ANUNCIO = "tb_announcement";

